### ISSUE TITLE
Build fails on Linux Zig 0.12.0 

### ISSUE THREAD

**Issue by PerikiyoXD** [nrdmn/uefi-examples#2]
```
error: root struct of file 'std' has no member named 'build'
const Builder = @import("std").build.Builder;
                ~~~~~~~~~~~~~~^~~~~~
```

**Comment by PerikiyoXD** [comment]
I'm working on a 0.12.0 port
